enableGlobalCache: true

enableImmutableInstalls: false

enableInlineBuilds: true

logFilters:
  - code: YN0062
    level: discard
  - code: YN0063
    level: discard
  - code: YN0076
    pattern: "*The darwin-x64 architecture is incompatible with this module, link skipped."
    level: discard

nodeLinker: node-modules

npmScopes:
  zuplo:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_NPM_TOKEN-remote}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
